LOCATION_MAPPING =
{
    -- Skills
    [9]     = {"@Full/Springleaf Path - Sacred Anemone & Harpy Archdemon/Sacred Anemone"},
    [10]    = {"@Full/Lun Tree Roots - Crescent Moonflower/Skill"},
    [20]    = {"@Full/Springleaf Path - Awakened Sacred Leaf & Bakman/Skill"},
    [131]   = {"@Full/Ashen Hinterlands - Lunar Attunement/Skill"},
    [194]   = {"@Full/Fairy Village - Spiral Shell/Skill"},

    -- Bosses
    [15]    = {"@Full/Springleaf Path - Gariser Demon/Boss"},
    [16]    = {"@Full/Springleaf Path - Raging Demon/Boss"},
    [17]    = {"@Full/Springleaf Path - Sacred Anemone & Harpy Archdemon/Harpy Archdemon"},
    [105]   = {"@Full/Demon Frontier - Accursed Autarch/Boss"},
    [114]   = {"@Full/Fairy Springs - Very Big Spider/Boss"},
    [150]   = {"@Full/Fairy Village - Viper Archdemon Sorrellia/Boss"},
    [171]   = {"@Full/Moonlight Repose - Remnant of an Unknown Phantasm & Phantasm Blade/Remnant of an Unknown Phantasm"},
    [188]   = {"@Full/Demon Frontier - Bloodthirsty Siblings/Boss"},
    [213]   = {"@Full/Meikan Village Windmill - Moon Goddess Lineth/Boss"},
    [255]   = {"@Full/Ashen Hinterlands - Tainted Serpent/Boss"},
    [259]   = {"@Full/Fount of Rebirth - Selin's Fear/Boss"},
    [260]   = {"@Full/Fount of Rebirth - Selin's Mendacity/Boss"},
    [261]   = {"@Full/Fount of Rebirth - Selin's Envy/Boss"},
    [262]   = {"@Full/Fount of Rebirth - Selin's Sorrow/Boss"},
    [278]   = {"@Full/Lun Tree Roots - Black Cat/Boss"},
    [364]   = {"@Full/Selin - Moon God Selin/Boss"},

    -- Extra
    [205]   = {"@Full/Demon Frontier - Mitchi Fast Travel/Skill"},

    -- Sigils
    [123]   = {"@Full/Cereza/Last Wish"},
    [400]   = {"@Full/Springleaf Path - Cloudy Blood/Sigil"},
    [401]   = {"@Full/Cereza/The Profiteer"},
    [402]   = {"@Full/Demon Frontier - Dark Healer/Sigil"},
    [403]   = {"@Full/Fount of Rebirth - Demilune Whisper/Sigil"},
    [404]   = {"@Full/Demon Frontier - Magic Blade/Sigil"},
    [405]   = {"@Full/Meikan Village - Perfect Chime/Sigil"},
    [406]   = {"@Full/Cereza/Queen of Light"},
    [408]   = {"@Full/Cereza/Strongfist"},
    [412]   = {"@Full/Springleaf Path - Living Edge/Sigil"},
    [419]   = {"@Full/Springleaf Path - The Fool & Dotted Berry 1/Sigil"},
    [420]   = {"@Full/Ashen Hinterlands - Living Blood/Sigil"},
    [422]   = {"@Full/Cereza/Fallen Hero"},
    [425]   = {"@Full/Fairy Springs - Resonance of Ifriya/Sigil"},
    [426]   = {"@Full/Cereza/The Collector"},
    [427]   = {"@Full/Koho Village - The Hunter/Sigil"},
    [430]   = {"@Full/Lun Tree Roots - The Arsonist/Sigil"},
    [431]   = {"@Full/Cereza/Chrysanth"},
    [432]   = {"@Full/Lun Tree Roots - The Fortunate/Sigil"},
    [433]   = {"@Full/Fairy Springs - Glazed Aegis/Sigil"},
    [434]   = {"@Full/Demon Frontier - Mending Resonance/Sigil"},
    [435]   = {"@Full/Fairy Springs - The Blessed/Sigil"},
    [436]   = {"@Full/Lun Tree Roots - Companionship Pact/Sigil"},
    [437]   = {"@Full/Cereza/Queen of Dusk"},
    [438]   = {"@Full/Old Sanctuary - The Sharpshooter/Sigil"},
    [439]   = {"@Full/Moonlight Repose - Remnant of an Unknown Phantasm & Phantasm Blade/Phantasm Blade"},
    [440]   = {"@Full/Springleaf Path - Pawn/Sigil"},
    [441]   = {"@Full/Fairy Village - Oracle/Sigil"},
    [442]   = {"@Full/Fount of Rebirth - Ascended Slash/Sigil"},
    [443]   = {"@Full/Meikan Village - Quintessence/Sigil"},
    [444]   = {"@Full/Old Sanctuary - Resolve/Sigil"},
    [445]   = {"@Full/Ashen Hinterlands - Serval & Dotted Berry 1/Sigil"},
    [446]   = {"@Full/Koho Village - Heavenly Lily & Welkin Leaf/Sigil"},
    [447]   = {"@Full/Ashen Hinterlands - Mudwalker/Sigil"},
    [448]   = {"@Full/Ashen Hinterlands - Hare/Sigil"},
    [449]   = {"@Full/Meikan Village Windmill - Trinary/Sigil"},

    -- Grimoires
    [338]   = {"@Full/Fairy Springs - Grimoire/Grimoire"},
    [339]   = {"@Full/Meikan Village Windmill - Tattered Grimoire/Grimoire"},
    [340]   = {"@Full/Fount of Rebirth - Dusty Grimoire/Grimoire"},

    -- Key Items
    [332]   = {"@Full/Old Sanctuary - Gold Moonlit Dust/Item"},
    [333]   = {"@Full/Moonlight Repose - Silver Moonlit Dust/Item"},
    [347]   = {"@Full/Meikan Village - Wooden Box/Item"},
    [356]   = {"@Full/Meikan Village - Windmill Key/Item"},

    -- Companions
    [304]   = {"@Full/Koho Village - Dotted Berry 1 & Grimalkin Spirit/Grimalkin Spirit"},
    [305]   = {"@Full/Springleaf Path - Awakened Sacred Leaf & Bakman/Bakman"},
    [306]   = {"@Full/Springleaf Path - Dotted Berry 3 & Lawa/Lawa"},
    [307]   = {"@Full/Demon Frontier - Floating Skull/Floating Skull"},
    [308]   = {"@Full/Meikan Village - Ducky/Ducky"},
    [309]   = {"@Full/Demon Frontier - Dotted Berry 2 & Vampire Bat/Vampire Bat"},
    [310]   = {"@Full/Lun Tree Roots - Simple Cube/Simple Cube"},
    [311]   = {"@Full/Old Sanctuary - Kaho/Kaho"},
    [312]   = {"@Full/Fount of Rebirth - Nun/Nun"},
    [330]   = {"@Full/Meikan Village Windmill - Cactus/Cactus"},

    -- Heavenly Lilies
    [2300]  = {"@Full/Fairy Village - Heavenly Lily 2/Heavenly Lily"},
    [2800]  = {"@Full/Springleaf Path - Heavenly Lily 1/Heavenly Lily"},
    [3800]  = {"@Full/Fairy Springs - Heavenly Lily 1/Heavenly Lily"},
    [8100]  = {"@Full/Old Sanctuary - Heavenly Lily 1/Heavenly Lily"},
    [8400]  = {"@Full/Springleaf Path - Heavenly Lily 2/Heavenly Lily"},
    [9400]  = {"@Full/Lun Tree Roots - Heavenly Lily 2/Heavenly Lily"},
    [11800] = {"@Full/Lun Tree Roots - Heavenly Lily 1/Heavenly Lily"},
    [12900] = {"@Full/Old Sanctuary - Heavenly Lily 2 & Fairy/Heavenly Lily"},
    [13000] = {"@Full/Ashen Hinterlands - Heavenly Lily 1/Heavenly Lily"},
    [15300] = {"@Full/Demon Frontier - Heavenly Lily 2 & Lunar Crystal Branch 4/Heavenly Lily"},
    [16600] = {"@Full/Demon Frontier - Heavenly Lily 3/Heavenly Lily"},
    [16900] = {"@Full/Demon Frontier - Heavenly Lily 1/Heavenly Lily"},
    [17200] = {"@Full/Moonlight Repose - Heavenly Lily 2/Heavenly Lily"},
    [24700] = {"@Full/Ashen Hinterlands - Heavenly Lily 3/Heavenly Lily"},
    [26400] = {"@Full/Koho Village - Heavenly Lily & Welkin Leaf/Heavenly Lily"},
    [28500] = {"@Full/Fount of Rebirth - Heavenly Lily 2/Heavenly Lily"},
    [28600] = {"@Full/Fount of Rebirth - Heavenly Lily 1/Heavenly Lily"},
    [30200] = {"@Full/Ashen Hinterlands - Heavenly Lily 2/Heavenly Lily"},
    [32200] = {"@Full/Fount of Rebirth - Heavenly Lily 4/Heavenly Lily"},
    [32300] = {"@Full/Fount of Rebirth - Heavenly Lily 3/Heavenly Lily"},
    [33300] = {"@Full/Meikan Village Windmill - Heavenly Lily 3 & Dotted Berry 3/Heavenly Lily"},
    [33400] = {"@Full/Meikan Village - Heavenly Lily 1/Heavenly Lily"},
    [33600] = {"@Full/Meikan Village - Heavenly Lily 2/Heavenly Lily"},
    [34300] = {"@Full/Fairy Village - Heavenly Lily 1 & Fairy/Heavenly Lily"},
    [34400] = {"@Full/Moonlight Repose - Heavenly Lily 1 & Fairy/Heavenly Lily"},

    -- Dotted Berries
    [2400]  = {"@Full/Lun Tree Roots - Dotted Berry 2 & Lunar Crystal Branch 5/Dotted Berry"},
    [2600]  = {"@Full/Lun Tree Roots - Dotted Berry 1/Dotted Berry"},
    [2700]  = {"@Full/Koho Village - Dotted Berry 1 & Grimalkin Spirit/Dotted Berry"},
    [2900]  = {"@Full/Springleaf Path - Dotted Berry 2/Dotted Berry"},
    [3000]  = {"@Full/Springleaf Path - The Fool & Dotted Berry 1/Dotted Berry"},
    [3100]  = {"@Full/Springleaf Path - Dotted Berry 4/Dotted Berry"},
    [3500]  = {"@Full/Fairy Springs - Dotted Berry 2/Dotted Berry"},
    [8900]  = {"@Full/Fairy Springs - Dotted Berry 3/Dotted Berry"},
    [11600] = {"@Full/Fairy Springs - Dotted Berry 1/Dotted Berry"},
    [14300] = {"@Full/Fairy Village - Dotted Berry/Dotted Berry"},
    [15200] = {"@Full/Demon Frontier - Dotted Berry 1/Dotted Berry"},
    [16500] = {"@Full/Demon Frontier - Dotted Berry 2 & Vampire Bat/Dotted Berry"},
    [17400] = {"@Full/Moonlight Repose - Dotted Berry/Dotted Berry"},
    [21900] = {"@Full/Ashen Hinterlands - Serval & Dotted Berry 1/Dotted Berry"},
    [24600] = {"@Full/Ashen Hinterlands - Dotted Berry 4/Dotted Berry"},
    [24900] = {"@Full/Ashen Hinterlands - Dotted Berry 2/Dotted Berry"},
    [28200] = {"@Full/Koho Village - Dora & Dotted Berry 2/Dotted Berry"},
    [33200] = {"@Full/Meikan Village Windmill - Dotted Berry 2/Dotted Berry"},
    [34800] = {"@Full/Fount of Rebirth - Dotted Berry 1/Dotted Berry"},
    [34900] = {"@Full/Fount of Rebirth - Dotted Berry 2/Dotted Berry"},
    [35600] = {"@Full/Ashen Hinterlands - Dotted Berry 3/Dotted Berry"},
    [35900] = {"@Full/Meikan Village - Dotted Berry 1/Dotted Berry"},
    [36000] = {"@Full/Meikan Village Windmill - Heavenly Lily 3 & Dotted Berry 3/Dotted Berry"},
    [36100] = {"@Full/Springleaf Path - Dotted Berry 3 & Lawa/Dotted Berry"},

    -- Lun Berries
    [3300]  = {"@Full/Springleaf Path - Lun Berry/Lun Berry"},
    [9500]  = {"@Full/Lun Tree Roots - Lun Berry/Lun Berry"},
    [11500] = {"@Full/Fairy Springs - Lun Berry/Lun Berry"},
    [13500] = {"@Full/Koho Village - Lun Berry/Lun Berry"},
    [22800] = {"@Full/Ashen Hinterlands - Lun Berry/Lun Berry"},
    [29500] = {"@Full/Demon Frontier - Lun Berry/Lun Berry"},
    [34100] = {"@Full/Fount of Rebirth - Lun Berry/Lun Berry"},

    -- Peaches
    [20100] = {"@Full/Springleaf Path - Peach & Fairy 2/Peach"},
    [20200] = {"@Full/Moonlight Repose - Peach/Peach"},
    [20300] = {"@Full/Fairy Springs - Peach/Peach"},
    [30300] = {"@Full/Ashen Hinterlands - Peach/Peach"},
    [33100] = {"@Full/Meikan Village - Peach/Peach"},

    -- Black Berries
    [5800]  = {"@Full/Lun Tree Roots - Black Berry/Black Berry"},
    [16400] = {"@Full/Demon Frontier - Black Berry/Black Berry"},

    -- Fairies
    [4100]  = {"@Full/Springleaf Path - Fairy 1/Fairy"},
    [4400]  = {"@Full/Springleaf Path - Fairy 3/Fairy"},
    [4600]  = {"@Full/Springleaf Path - Fairy 4/Fairy"},
    [4700]  = {"@Full/Fairy Springs - Fairy 1/Fairy"},
    [5100]  = {"@Full/Lun Tree Roots - Fairy 2/Fairy"},
    [5400]  = {"@Full/Lun Tree Roots - Fairy 4/Fairy"},
    [5700]  = {"@Full/Lun Tree Roots - Fairy 5/Fairy"},
    [8700]  = {"@Full/Lun Tree Roots - Fairy 1/Fairy"},
    [8800]  = {"@Full/Lun Tree Roots - Fairy 3/Fairy"},
    [9100]  = {"@Full/Fairy Springs - Fairy 4/Fairy"},
    [9300]  = {"@Full/Fairy Springs - Fairy 2/Fairy"},
    [13700] = {"@Full/Fairy Springs - Fairy 3/Fairy"},
    [16200] = {"@Full/Demon Frontier - Fairy 3 & Lunar Crystal Branch 3/Fairy"},
    [16800] = {"@Full/Demon Frontier - Fairy 4/Fairy"},
    [22100] = {"@Full/Ashen Hinterlands - Fairy 1 & Lunar Crystal Branch 1/Fairy"},
    [22400] = {"@Full/Ashen Hinterlands - Fairy 2 & Lunar Crystal Branch 2/Fairy"},
    [22900] = {"@Full/Ashen Hinterlands - Fairy 3/Fairy"},
    [23800] = {"@Full/Ashen Hinterlands - Fairy 4/Fairy"},
    [28700] = {"@Full/Fount of Rebirth - Fairy 2/Fairy"},
    [28800] = {"@Full/Fount of Rebirth - Fairy 1/Fairy"},
    [30000] = {"@Full/Meikan Village - Fairy/Fairy"},
    [30100] = {"@Full/Meikan Village Windmill - Fairy/Fairy"},
    [34200] = {"@Full/Fairy Village - Heavenly Lily 1 & Fairy/Fairy"},
    [34600] = {"@Full/Moonlight Repose - Heavenly Lily 1 & Fairy/Fairy"},
    [35100] = {"@Full/Demon Frontier - Fairy 1 & Fairy 2/Fairy 2"},
    [35200] = {"@Full/Demon Frontier - Fairy 1 & Fairy 2/Fairy 1"},
    [35400] = {"@Full/Springleaf Path - Peach & Fairy 2/Fairy"},
    [35300] = {"@Full/Old Sanctuary - Heavenly Lily 2 & Fairy/Fairy"},
    [35500] = {"@Full/Demon Frontier - Fairy 5/Fairy"},
    [35700] = {"@Full/Ashen Hinterlands - Fairy 5/Fairy"},

    -- Lunar Crystal Branches
    [4000]  = {"@Full/Springleaf Path - Lunar Crystal Branch 1/Lunar Crystal Branch"},
    [4200]  = {"@Full/Springleaf Path - Lunar Crystal Branch 4/Lunar Crystal Branch"},
    [4300]  = {"@Full/Springleaf Path - Lunar Crystal Branch 3/Lunar Crystal Branch"},
    [4500]  = {"@Full/Springleaf Path - Lunar Crystal Branch 5/Lunar Crystal Branch"},
    [4800]  = {"@Full/Fairy Springs - Lunar Crystal Branch 3/Lunar Crystal Branch"},
    [4900]  = {"@Full/Fairy Springs - Lunar Crystal Branch 2/Lunar Crystal Branch"},
    [5000]  = {"@Full/Springleaf Path - Lunar Crystal Branch 2/Lunar Crystal Branch"},
    [5200]  = {"@Full/Lun Tree Roots - Lunar Crystal Branch 3/Lunar Crystal Branch"},
    [5300]  = {"@Full/Lun Tree Roots - Lunar Crystal Branch 2/Lunar Crystal Branch"},
    [5500]  = {"@Full/Lun Tree Roots - Lunar Crystal Branch 4/Lunar Crystal Branch"},
    [5600]  = {"@Full/Fairy Springs - Lunar Crystal Branch 1/Lunar Crystal Branch"},
    [8300]  = {"@Full/Lun Tree Roots - Lunar Crystal Branch 1/Lunar Crystal Branch"},
    [8200]  = {"@Full/Koho Village - Lunar Crystal Branch/Lunar Crystal Branch"},
    [9000]  = {"@Full/Fairy Springs - Lunar Crystal Branch 4/Lunar Crystal Branch"},
    [9600]  = {"@Full/Lun Tree Roots - Dotted Berry 2 & Lunar Crystal Branch 5/Lunar Crystal Branch"},
    [11900] = {"@Full/Moonlight Repose - Lunar Crystal Branch/Lunar Crystal Branch"},
    [12400] = {"@Full/Old Sanctuary - Lunar Crystal Branch 1/Lunar Crystal Branch"},
    [12500] = {"@Full/Old Sanctuary - Lunar Crystal Branch 2 & Lunar Crystal Branch 3 & Lunar Crystal Branch 4/Lunar Crystal Branch 2"},
    [12600] = {"@Full/Old Sanctuary - Lunar Crystal Branch 2 & Lunar Crystal Branch 3 & Lunar Crystal Branch 4/Lunar Crystal Branch 3"},
    [12700] = {"@Full/Old Sanctuary - Lunar Crystal Branch 2 & Lunar Crystal Branch 3 & Lunar Crystal Branch 4/Lunar Crystal Branch 4"},
    [13300] = {"@Full/Fairy Springs - Lunar Crystal Branch 5/Lunar Crystal Branch"},
    [15400] = {"@Full/Demon Frontier - Lunar Crystal Branch 1/Lunar Crystal Branch"},
    [16100] = {"@Full/Demon Frontier - Lunar Crystal Branch 2/Lunar Crystal Branch"},
    [16300] = {"@Full/Demon Frontier - Fairy 3 & Lunar Crystal Branch 3/Lunar Crystal Branch"},
    [17800] = {"@Full/Demon Frontier - Heavenly Lily 2 & Lunar Crystal Branch 4/Lunar Crystal Branch"},
    [22200] = {"@Full/Ashen Hinterlands - Fairy 1 & Lunar Crystal Branch 1/Lunar Crystal Branch"},
    [22500] = {"@Full/Ashen Hinterlands - Lunar Crystal Branch 3 & Lunar Crystal Branch 4/Lunar Crystal Branch 3"},
    [22600] = {"@Full/Ashen Hinterlands - Fairy 2 & Lunar Crystal Branch 2/Lunar Crystal Branch"},
    [22700] = {"@Full/Ashen Hinterlands - Lunar Crystal Branch 3 & Lunar Crystal Branch 4/Lunar Crystal Branch 4"},
    [24800] = {"@Full/Ashen Hinterlands - Lunar Crystal Branch 5/Lunar Crystal Branch"}
}
